en:
  preferred_language_on_setup_enabled:
    default: true
    client: false
    type: bool
    description: "Enable preferred language setup via user field on signup"

  selected_languages:
    type: list
    default:
      - en
    choices:
      - "en"
      - "sv"
      - "fr"
      - "de"
      - "es"
      - "it"
      - "ja"
      - "zh_CN"
      - "ru"
      - "ar"
      - "pt"
      - "tr"
      - "nl"
      - "ko"
      - "pl"
      - "uk"
      - "vi"
      - "hi"
      - "he"
      - "ro"
      - "cs"
      - "el"
      - "fi"
      - "no"
      - "da"
      - "hu"
      - "id"
      - "th"
      - "bg"
      - "ms"
      - "sk"
      - "sr"
      - "hr"
      - "lt"
      - "lv"
      - "et"
      - "sl"
    client: false
    description: "Select which languages will be available in the user field dropdown at signup"
    