preferred_language_on_setup_enabled:
  default: true
  client: false
  type: bool

preferred_language_on_setup_locales:
  type: list
  list_type: compact
  default: ["en"]
  client: false
  choices:
    - en
    - sv